server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: weather-application

application:
  weather-api:
    base-url: http://api.weatherapi.com/v1
    current-weather-uri: /current.json?lang={language}&q={city}&key={key}
    api-key: e8c4123c9de04ef3afd50459230710
    default-language: ru

resilience4j:
  ratelimiter:
    instances:
      weather-api-limiter:
        limit-for-period: 2
        limit-refresh-period: 10s
        timeout-duration: 0

springdoc:
  swagger-ui:
    path: swagger.html

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
