server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: weather-application
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/data/db
    username: h2
    password: h2
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
      path: /db

springdoc:
  swagger-ui:
    path: swagger.html

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
