server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: weather-application
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db;INIT=CREATE SCHEMA IF NOT EXISTS weather;DATABASE_TO_LOWER=true;
    username: ${h2.username}
    password: ${h2.password}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
      schema: weather
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/migrations/liquibase-changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.datasource.hikari.schema}

cache:
  course:
    size: 10 # максимальное количество элементов в кэше

springdoc:
  swagger-ui:
    path: swagger.html


management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  server:
    port: 8081
